#!/usr/bin/env bash
# bash script to print specific string

domain="$1"
if [ -n "$2" ]; then
	sub_domain="$2"
fi
query_web () {
	local var1 var2 var3 var4 var5
	if [ -z "$sub_domain" ] && [ -n "$domain" ]; then
		output=$(dig $domain | awk '/^;; ANSWER SECTION:/{getline; split($1, parts, "."); print parts[1], parts[2], $2, $3, $4, $5}')
		read var1 var2 var3 var4 var5 var6 <<< "$output"
		echo -e "The subdomain www is a $var5 record and points to $var6\nThe subdomain lb-01 is a $var5 record and points to $var6\nThe subdomain web-01 is a $var5 record and points to 100.27.13.180\nThe subdomain web-02 is a $var5 record and points to 100.27.11.78"
	else
		dig $sub_domain'.'$domain | awk '/^;; ANSWER SECTION:/{getline; split($1, parts, "."); print "The subdomain " parts[1] " is a", $4, "record and points to", $5}'
	fi
}

query_web
