#!/usr/bin/env bash
# recieves argument from the cmd

if [ "$#" -lt 3 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

PATH_OF_FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEYS="$4"

scp -o StrictHostKeyChecking=no -i "$SSH_KEYS" "$PATH_OF_FILE" "$USERNAME"@"$IP":~/
