#!/usr/bin/env bash
#Install nginx web server and Redirection
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i 's#server_name _;#server_name _;\n\n\tlocation = /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}#g' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page - 404" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i '/^\slocation.*/i\terror_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo service nginx start
