#!/usr/bin/env bash
# configure nginx as a system account
apt update
apt install nginx
useradd --system nginx
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/nginx
sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
