#!/usr/bin/env bash
# configure nginx as a system account
apt update
# if command -v nginx; then
apt-get install nginx -y
useradd -r nginx
sed -i '1s/.*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
service nginx start
